arguments.o: arguments.cc string.h defines.h tokenizer.h arguments.h \
  exception.h
filesystem.o: filesystem.cc exception.h defines.h system.h filesystem.h
inifile.o: inifile.cc exception.h defines.h inifile.h string.h refptr.h \
  atomic.h
system.o: system.cc system.h defines.h
