DMRecon.o: DMRecon.cpp DMRecon.h ../mve/bundlefile.h ../util/refptr.h \
  ../util/defines.h ../util/atomic.h ../mve/defines.h ../mve/camera.h \
  ../mve/trianglemesh.h ../math/vector.h ../math/defines.h \
  ../math/algo.h ../mve/image.h ../mve/imagebase.h ../util/string.h \
  ../mve/scene.h ../mve/view.h defines.h PatchOptimization.h \
  PatchSampler.h Settings.h SingleView.h ../math/matrix.h \
  LocalViewSelection.h ViewSelection.h Progress.h GlobalViewSelection.h \
  ../mve/imagetools.h ../util/exception.h ../math/accum.h ../util/fs.h
GlobalViewSelection.o: GlobalViewSelection.cpp GlobalViewSelection.h \
  SingleView.h ../math/vector.h ../math/defines.h ../math/algo.h \
  ../math/matrix.h ../mve/view.h ../util/refptr.h ../util/defines.h \
  ../util/atomic.h ../mve/defines.h ../mve/camera.h ../mve/imagebase.h \
  ../util/string.h ../mve/image.h ../mve/bundlefile.h \
  ../mve/trianglemesh.h defines.h ViewSelection.h Settings.h mvstools.h
LocalViewSelection.o: LocalViewSelection.cpp ../math/defines.h \
  ../util/refptr.h ../util/defines.h ../util/atomic.h \
  LocalViewSelection.h ViewSelection.h defines.h ../math/vector.h \
  ../math/algo.h Settings.h PatchSampler.h SingleView.h ../math/matrix.h \
  ../mve/view.h ../mve/defines.h ../mve/camera.h ../mve/imagebase.h \
  ../util/string.h ../mve/image.h ../mve/bundlefile.h \
  ../mve/trianglemesh.h mvstools.h
PatchOptimization.o: PatchOptimization.cpp ../util/string.h \
  ../util/defines.h ../math/algo.h ../math/defines.h ../math/matrix.h \
  ../math/vector.h ../math/matrixtools.h PatchOptimization.h \
  ../util/refptr.h ../util/atomic.h defines.h PatchSampler.h Settings.h \
  SingleView.h ../mve/view.h ../mve/defines.h ../mve/camera.h \
  ../mve/imagebase.h ../mve/image.h ../mve/bundlefile.h \
  ../mve/trianglemesh.h LocalViewSelection.h ViewSelection.h
PatchSampler.o: PatchSampler.cpp ../math/defines.h ../math/matrix.h \
  ../math/algo.h ../math/vector.h defines.h mvstools.h ../mve/image.h \
  ../util/refptr.h ../util/defines.h ../util/atomic.h ../mve/defines.h \
  ../mve/imagebase.h ../util/string.h SingleView.h ../mve/view.h \
  ../mve/camera.h ../mve/bundlefile.h ../mve/trianglemesh.h \
  PatchSampler.h Settings.h
Settings.o: Settings.cpp Settings.h defines.h ../math/vector.h \
  ../math/defines.h ../math/algo.h
SingleView.o: SingleView.cpp ../mve/imagefile.h ../mve/defines.h \
  ../mve/image.h ../util/refptr.h ../util/defines.h ../util/atomic.h \
  ../math/algo.h ../math/defines.h ../mve/imagebase.h ../util/string.h \
  ../mve/imagetools.h ../util/exception.h ../math/accum.h \
  ../mve/camera.h ../mve/plyfile.h ../mve/view.h ../mve/trianglemesh.h \
  ../math/vector.h ../util/fs.h defines.h SingleView.h ../math/matrix.h \
  ../mve/bundlefile.h
mvstools.o: mvstools.cpp mvstools.h defines.h ../math/vector.h \
  ../math/defines.h ../math/algo.h ../math/matrix.h ../mve/image.h \
  ../util/refptr.h ../util/defines.h ../util/atomic.h ../mve/defines.h \
  ../mve/imagebase.h ../util/string.h SingleView.h ../mve/view.h \
  ../mve/camera.h ../mve/bundlefile.h ../mve/trianglemesh.h \
  ../mve/imagetools.h ../util/exception.h ../math/accum.h \
  ../mve/imagefile.h
