#ifndef DMFUSION_DEFINES_HEADER
#define DMFUSION_DEFINES_HEADER

#define DMFUSION_NAMESPACE_BEGIN namespace dmf {
#define DMFUSION_NAMESPACE_END }

/** Depthmap fusion library. */
DMFUSION_NAMESPACE_BEGIN DMFUSION_NAMESPACE_END

#endif /* DMFUSION_DEFINES_HEADER */
