#include <iostream>

#include "util/system.h"

#include "mve/image_io.h"
#include "mve/image_exif.h"
#include "mve/image_drawing.h"
#include "mve/view.h"

int
main (int argc, char** argv)
{

#if 1
    std::string fname = "/data/dev/phd/datasets/mve_persil_maus/views/view_0000.mve";
    mve::View view;
    view.load_view_from_mve_file(fname);
    view.save_view_as("/tmp/testview.mve");
#endif

#if 0 // create view test
    std::string path = "/tmp/mve2_tests/views/view_0001.mve";
    try
    {
        std::cout << "TEST: Creating view..." << std::endl;
        mve::ViewIO view_io;
        view_io.set_value("view.name", "view_0001");
        view_io.set_value("view.comment", "Generated by makescene");
        view_io.set_value("original.radial_distortion", "1.0 -2.2");
        view_io.set_value("view.id", "0");

        mve::ByteImage::Ptr img = mve::ByteImage::create(11, 11, 3);
        img->fill(128);
        img->at(5, 5, 0) = 255;
        img->at(5, 5, 1) = 0;
        img->at(5, 5, 2) = 0;
        view_io.add_image(img, "testimage");

        mve::ByteImage::Ptr blob = mve::ByteImage::create(5, 1, 1);
        blob->at(0) = 'a';
        blob->at(1) = 'b';
        blob->at(2) = '0';
        blob->at(3) = '1';
        blob->at(4) = '\n';
        view_io.add_blob(blob, "myblob");

        view_io.save_view_as(path);
    }
    catch (std::exception& e)
    {
        std::cerr << "Exception: " << e.what() << std::endl;
    }
#endif

#if 0 // read view and change image test
    std::string path = "/data/dev/phd/datasets/mve2_tests/views/view_0001.mve";
    try
    {
        std::cout << "TEST: Loading view..." << std::endl;
        mve::ViewIO view_io;
        view_io.load_view(path);
        //view_io.debug_print();

        mve::ImageBase::Ptr image = view_io.get_image("testimage");
        mve::ByteImage::Ptr img = image;
        uint8_t color_red[3] = { 255, 0, 0 };
        mve::image::draw_circle(*img, 5, 5, 2, color_red);
        view_io.set_image(img, "testimage");
        view_io.set_value("comment", "Just a simple view");


        view_io.save_view();

    }
    catch (std::exception& e)
    {
        std::cerr << "Exception: " << e.what() << std::endl;
    }
#endif

#if 0 // read view and debug print
    std::string path = "/data/dev/phd/datasets/mve2_tests/views/view_0001.mve";
    mve::ViewIO view_io(path);
    view_io.debug_print();
#endif

#if 0
    /* Provoke view corruption. */

    /*
     * Failure case 1
     * --------------
     * P1: Read view
     * P2: Read view
     * P1: Modifiy and save view
     * P2: Read embedding (may read wrong data because view changed)
     */

    {
        /* Generate a view. */
        mve::ByteImage::Ptr img1 = mve::image::load_file("../../data/testimages/test_rgb_32x32.png");
        mve::ByteImage::Ptr img2 = mve::image::load_file("../../data/testimages/test_grey_32x32.png");
        mve::View::Ptr view = mve::View::create();
        view->set_name("View 123");
        view->set_camera(mve::CameraInfo());
        view->add_image("color-pattern", img1);
        view->add_image("gray-pattern", img2);
        view->save_mve_file_as("/tmp/myview.mve");
    }

    {
        /* Simulate two competing processes. */
        mve::View::Ptr view1 = mve::View::create("/tmp/myview.mve");
        mve::View::Ptr view2 = mve::View::create("/tmp/myview.mve");

        /* Change view1. */
        mve::ByteImage::Ptr img1 = mve::image::load_file("../../data/testimages/diaz_color.png");
        view1->set_image("color-pattern", img1);
        view1->save_mve_file();

        /* Retrieve image from view2. */
        mve::ByteImage::Ptr img2 = view2->get_byte_image("color-pattern");
        mve::image::save_file(img2, "/tmp/myresult.png");
    }


    /*
     * Failure case 2
     * --------------
     * P1 and P2: read view
     * P1 adds embeddings, saves view
     * P2 adds embeddings, saves view (issues "save as",
     *   reads uncached embeddings withoug re-reading (changed) headers)
     *
     * Practical failure case: MVS on two scales on the same view:
     * ./dmrecon -s1 -l0 DATASET_DIR
     * ./dmrecon -s2 -l0 DATASET_DIR
     */




#endif


#if 0
#   define MVE_FILE "/tmp/myscene/views/view_0000.mve"
#   define VIEW_CLASS View

    std::cout << "--- View tests ---" << std::endl;
    if (argc != 2)
    {
        std::cout << "Pass a command!" << std::endl;
        return 1;
    }

    if (std::string(argv[1]) == "build")
    {
        mve::ByteImage::Ptr img1;
        img1 = mve::image::load_file("../../data/testimages/test_rgb_32x32.png");

        mve::ByteImage::Ptr img2;
        img2 = mve::image::load_file("../../data/testimages/test_grey_32x32.png");

        mve::VIEW_CLASS::Ptr view(mve::VIEW_CLASS::create());
        view->set_name("View 123");
        view->set_camera(mve::CameraInfo());

        view->add_image("color-pattern", img1);
        view->add_image("gray-pattern", img2);

        view->save_mve_file_as(MVE_FILE);
        return 0;
    }

    mve::VIEW_CLASS::Ptr view(mve::VIEW_CLASS::create());
    view->load_mve_file(MVE_FILE);
    view->print_debug(); std::cout << std::endl;

    if (std::string(argv[1]) == "name-modify")
    {
        view->set_name("testview123");
        view->save_mve_file();
    }

    if (std::string(argv[1]) == "addimage")
    {
        mve::ByteImage::Ptr img1;
        img1 = mve::image::load_file("../../data/testimages/diaz_color.png");
        view->set_image("testimage", img1);

        view->save_mve_file();
        view->save_mve_file();
    }

    if (std::string(argv[1]) == "noop")
    {
        view->save_mve_file();
    }

    if (std::string(argv[1]) == "exif")
    {
        mve::ByteImage::Ptr exif = view->get_data("exif");
        char const* exif_data = reinterpret_cast<char const*>(exif->begin());
        mve::image::ExifInfo einfo;
        einfo = mve::image::exif_extract(exif_data, exif->width());
        mve::image::exif_debug_print(einfo);
    }

    if (std::string(argv[1]) == "export")
    {
        mve::ByteImage::Ptr img(view->get_byte_image("color-pattern"));
        if (img == NULL)
            std::cout << "Warning: Image was not properly loaded" << std::endl;
        else
        {
            std::cout << "Saving image to file..." << std::endl;
            mve::image::save_file(img, "/tmp/colorpattern.png");
        }
    }

    if (std::string(argv[1]) == "cachecleanup")
    {
        mve::ByteImage::Ptr keep(view->get_byte_image("color-pattern"));
        view->get_byte_image("testimage");
        view->print_debug(); std::cout << std::endl;
        view->cache_cleanup();
        view->print_debug(); std::cout << std::endl;
    }

    if (std::string(argv[1]) == "writeback")
    {
        mve::ByteImage::Ptr keep(view->get_byte_image("color-pattern"));
        view->set_image("color-pattern", keep);
        view->print_debug(); std::cout << std::endl;
        keep.reset();
        view->cache_cleanup();
        view->print_debug(); std::cout << std::endl;

        view->save_mve_file();
    }

    if (std::string(argv[1]) == "nastysave")
    {
        //mve::ByteImage::Ptr keep(view->get_byte_image("color-pattern"));
        //view->set_image("color-pattern", keep);
        view->save_mve_file_as(MVE_FILE);
    }


    if (std::string(argv[1]) == "stresstest")
    {
        for (int j = 0; j < 10; ++j)
        {
#pragma omp parallel for
            for (int i = 0; i < 2; ++i)
            {
                view->get_image("testimage");
            }
            view->cache_cleanup();
        }
    }
#endif

    return 0;
}


