bundlefile.o: bundlefile.cc ../util/exception.h ../util/defines.h \
  ../util/string.h ../mve/bundlefile.h ../util/refptr.h ../util/atomic.h \
  ../mve/defines.h ../mve/camera.h ../mve/trianglemesh.h \
  ../math/vector.h ../math/defines.h ../math/algo.h
camera.o: camera.cc ../math/matrixtools.h ../math/defines.h \
  ../math/matrix.h ../math/algo.h ../math/vector.h ../mve/camera.h \
  ../mve/defines.h
depthmap.o: depthmap.cc ../math/defines.h ../math/matrix.h ../math/algo.h \
  ../math/vector.h ../mve/vertexinfo.h ../util/refptr.h \
  ../util/defines.h ../util/atomic.h ../mve/defines.h \
  ../mve/trianglemesh.h ../mve/depthmap.h ../mve/camera.h ../mve/image.h \
  ../mve/imagebase.h ../util/string.h ../mve/meshtools.h \
  ../mve/bilateral.h ../math/accum.h
imageexif.o: imageexif.cc ../mve/imageexif.h ../mve/defines.h
imagefile.o: imagefile.cc ../util/endian.h ../util/defines.h \
  ../util/exception.h ../util/string.h ../mve/imagefile.h \
  ../mve/defines.h ../mve/image.h ../util/refptr.h ../util/atomic.h \
  ../math/algo.h ../math/defines.h ../mve/imagebase.h
imagetools.o: imagetools.cc ../mve/camera.h ../mve/defines.h \
  ../mve/imagetools.h ../util/exception.h ../util/defines.h \
  ../math/accum.h ../math/defines.h ../math/algo.h ../mve/image.h \
  ../util/refptr.h ../util/atomic.h ../mve/imagebase.h ../util/string.h
marching.o: marching.cc ../mve/defines.h
meshtools.o: meshtools.cc ../util/exception.h ../util/defines.h \
  ../util/string.h ../math/algo.h ../math/defines.h ../math/vector.h \
  ../mve/offfile.h ../mve/defines.h ../mve/trianglemesh.h \
  ../util/refptr.h ../util/atomic.h ../mve/plyfile.h ../mve/image.h \
  ../mve/imagebase.h ../mve/camera.h ../mve/view.h ../mve/pbrtfile.h \
  ../mve/vertexinfo.h ../mve/meshtools.h ../math/matrix.h
offfile.o: offfile.cc ../math/vector.h ../math/defines.h ../math/algo.h \
  ../util/exception.h ../util/defines.h ../mve/offfile.h \
  ../mve/defines.h ../mve/trianglemesh.h ../util/refptr.h \
  ../util/atomic.h
pbrtfile.o: pbrtfile.cc ../util/exception.h ../util/defines.h \
  ../mve/pbrtfile.h ../mve/trianglemesh.h ../math/vector.h \
  ../math/defines.h ../math/algo.h ../util/refptr.h ../util/atomic.h \
  ../mve/defines.h
plyfile.o: plyfile.cc ../util/exception.h ../util/defines.h \
  ../util/tokenizer.h ../util/endian.h ../math/vector.h \
  ../math/defines.h ../math/algo.h ../math/matrix.h ../mve/depthmap.h \
  ../mve/defines.h ../mve/camera.h ../mve/image.h ../util/refptr.h \
  ../util/atomic.h ../mve/imagebase.h ../util/string.h \
  ../mve/trianglemesh.h ../mve/plyfile.h ../mve/view.h
scene.o: scene.cc ../util/exception.h ../util/defines.h ../util/timer.h \
  ../util/filesystem.h ../mve/scene.h ../util/refptr.h ../util/atomic.h \
  ../mve/defines.h ../mve/view.h ../mve/camera.h ../mve/imagebase.h \
  ../util/string.h ../mve/image.h ../math/algo.h ../math/defines.h \
  ../mve/bundlefile.h ../mve/trianglemesh.h ../math/vector.h
sift.o: sift.cc ../util/timer.h ../util/defines.h ../math/matrix.h \
  ../math/defines.h ../math/algo.h ../math/vector.h \
  ../math/matrixtools.h ../mve/imagefile.h ../mve/defines.h \
  ../mve/image.h ../util/refptr.h ../util/atomic.h ../mve/imagebase.h \
  ../util/string.h ../mve/imagetools.h ../util/exception.h \
  ../math/accum.h ../mve/camera.h ../mve/sift.h
trianglemesh.o: trianglemesh.cc ../math/defines.h ../mve/trianglemesh.h \
  ../math/vector.h ../math/algo.h ../util/refptr.h ../util/defines.h \
  ../util/atomic.h ../mve/defines.h
vertexinfo.o: vertexinfo.cc ../mve/vertexinfo.h ../util/refptr.h \
  ../util/defines.h ../util/atomic.h ../mve/defines.h \
  ../mve/trianglemesh.h ../math/vector.h ../math/defines.h \
  ../math/algo.h
view.o: view.cc ../util/tokenizer.h ../util/defines.h ../util/exception.h \
  ../util/filesystem.h ../util/string.h ../mve/image.h ../util/refptr.h \
  ../util/atomic.h ../math/algo.h ../math/defines.h ../mve/defines.h \
  ../mve/imagebase.h ../mve/view.h ../mve/camera.h
volume.o: volume.cc ../math/vector.h ../math/defines.h ../math/algo.h \
  ../mve/marchingtets.h ../mve/defines.h ../mve/trianglemesh.h \
  ../util/refptr.h ../util/defines.h ../util/atomic.h \
  ../mve/marchingcubes.h ../mve/image.h ../mve/imagebase.h \
  ../util/string.h ../mve/volume.h
